platform :ios,'8.0'
pod "AFNetworking"
pod "MJExtension"
pod "SDWebImage"
pod "MJRefresh"
pod "SVProgressHUD"
pod "pop"
pod "MBProgressHUD"
pod "DACircularProgress"
pod "Masonry"
pod 'SVProgressHUD', '~> 1.1.3'